@port = 3001
@default = http://localhost:{{port}}

#### Testing
GET {{default}}/api/user

#### User Sign up
POST {{default}}/api/user
Content-Type: application/json

{
    "firstname": "",
    "lastname": "lastname",
    "username": "User #none",
    "email": "something@gmail.com",
    "password": "User #12"
} 

#### User Login
POST {{default}}/api/login
Content-Type: application/json

{
    "username": "User #1",
    "password": "User #12"
}